require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - spec/**/*

Metrics/MethodLength:
  Max: 30
